# Site settings
title: OctoPrint Plugin Repository
short_title: Plugin Repo
email: contact@octoprint.org
description: The official OctoPrint Plugin Repository
external: "https://plugins.octoprint.org"
#external: "http://localhost:4000"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://plugins.octoprint.org" # the base hostname & protocol for your site
twitter_username: OctoPrint3D
github_username:  OctoPrint

# Build settings
highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

collections:
  plugins:
    output: true

    # if you ever change this, also change the /plugins/ and / stripping routine in plugins.json!
    permalink: /plugins/:path/

exclude:
- CNAME
- Gemfile
- Gemfile.lock
- vendor
- "*.iml"
- .rvmrc
- .rbenv-version
- node_modules
