# Site settings
title: OctoPrint Plugin Repository
short_title: Plugin Repo
email: contact@octoprint.org
description: The official OctoPrint Plugin Repository
external: "https://plugins.octoprint.org"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://plugins.octoprint.org" # the base hostname & protocol for your site
twitter_username: OctoPrint3D
github_username: OctoPrint

# Build settings
highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

collections:
  plugins:
    output: true

    # if you ever change this, also change the /plugins/ and / stripping routine in plugins.json!
    permalink: /plugins/:path/

carbon: //cdn.carbonads.com/carbon.js?serve=CK7DT237&placement=pluginsoctoprintorg

exclude:
- CNAME
- Gemfile
- Gemfile.lock
- vendor
- "*.iml"
- .rvmrc
- .rbenv-version
- node_modules
- fetch_yt_preview
- README.md
- .github
- .asset-cache
- _build
- .editorconfig
- .git-blame-ignore-revs
- .pre-commit-config.yaml
- black.toml

plugins:
- jekyll-redirect-from
- jekyll-assets

assets:
  digest: true
  compress:
    css: false
    js: false
  assets:
    - "**.css"
    - "**.js"
  sources:
    - "_assets"

twitterlink: https://twitter.com/OctoPrint3D
facebooklink: https://facebook.com/OctoPrint
youtubelink: https://www.youtube.com/c/OctoPrint3D
